import type { NewsSource } from '@/types/newsIngestion';

/**
 * Normalized corporate announcement — the single contract shared across
 * providers, persistence, Socket.io, and future AI/scoring modules.
 *
 * Provider-specific fields must NOT leak past the provider + normalizer layer.
 */
export interface Announcement {
  source: NewsSource;
  symbol: string;
  companyName: string;
  headline: string;
  description: string;
  publishedAt: Date;
  url?: string;
  /** SHA-256 dedup key — generated by DuplicateDetectionService */
  fingerprint: string;
  /** Complete raw JSON from the provider — never discarded */
  rawData: unknown;
  createdAt: Date;
}

/**
 * Input shape before fingerprint assignment (normalizer output).
 * DuplicateDetectionService adds `fingerprint` and `createdAt`.
 */
export type AnnouncementDraft = Omit<Announcement, 'fingerprint' | 'createdAt'>;

/** Future AI pipeline status — maps to nullable DB columns */
export type ProcessingStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'skipped';

/**
 * Database record shape including nullable columns reserved for future modules.
 * AI / scoring fields remain NULL until those modules are implemented.
 */
export interface PersistedAnnouncement extends Announcement {
  id: string;
  eventType: string | null;
  impact: string | null;
  confidence: number | null;
  score: number | null;
  processingStatus: ProcessingStatus;
  aiVersion: string | null;
}
